### ISSUE TITLE
[FEATURE] 장바구니 추가 후 보이는 dialog UI 구성하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-banchan-05#10]
### 📌 내용
상세 화면에서 장바구니에 반찬 상품 추가 성공 시,
화면에 다이얼로그 보여주기(background dim 처리)
```
다른 곳에서 공통으로 사용되므로 별도의 view로 관리하기
```

### 🛠 ToDo
- [x] 주문하기 버튼 성공 시, custom dialog 보여주기(아직 빈화면)
- [x] dialog의 UI 구성하기
- [x] '장바구니 확인' 버튼 클릭 시, 장바구니 화면으로 이동하기
- [x] '계속 쇼핑하기' 버튼 클릭 시, dialog만 제거해주기
