### ISSUE TITLE
[REFACTOR] 최근 본 상품 페이징 코드 개선

### ISSUE THREAD

**Issue by eshc123** [woowa-techcamp-2022/android-banchan-05#112]
### 📌 내용
#105 PR 코드 개선

### 🛠 ToDo
- [ ] RecentRepositoryImpl - 쉼표 삭제
- [ ] RecentViewModel - _recentMenus 수정(https://github.com/woowa-techcamp-2022/android-banchan-05/pull/105#discussion_r954835970 참고)
- [ ] RecentPagingAdapter - areContentsTheSame 수정
- [ ] RecentFragment - RecyclerView lifecycle 수정
- [ ] RecentPagingAdapter - viewHolder 재사용
- [ ] PagingAdapter - 템플릿타입
