### ISSUE TITLE
[FIX] 버그 및 기능 개선

### ISSUE THREAD

**Issue by eshc123** [woowa-techcamp-2022/android-banchan-05#115]
### 📌 내용
여러 화면에서 버그 및 기능 개선

### 🛠 ToDo
- [ ] 메인 요리 - 상세화면 - 메인 요리일 때 다시 로드 하는 문제
- [ ] Cart화면 - 장바구니 아이템 변경 시 최근 본 상품 갱신 문제
- [ ] Appbar - 이벤트마다 갱신되는 문제
