### ISSUE TITLE
[FEATURE] 네트워크 상태에 따른 UI 처리해주기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-banchan-05#116]
### 📌 내용
네트워크가 연결되어 있지 않을 때 사용자와 상호작용할 수 없도록 dismiss할 수 없는 Dialog를 띄워줍니다.
다시 네트워크가 정상 연결되면 사용가능하도록 dialog를 dismiss 시켜줍니다.

### 🛠 ToDo
- [x] MainActivity에서 네트워크 상태를 읽어올 수 있는 코드 추가
- [x] 버튼 없는 Dialog UI 구성하기
- [x] 버튼 없는 Dialog 보여주기
- [x] 네트워크 연결이 되어있지 않을 때만 Dialog 보여주기
