### ISSUE TITLE
[FEATURE] 메인 '기획전 이외 탭' 화면 코드 개선 사항

### ISSUE THREAD

**Issue by eshc123** [woowa-techcamp-2022/android-banchan-05#23]
### 📌 내용
메인 '기획전 이외 탭' 화면 구현 중 생긴 코드 개선 사항

### 🛠 ToDo
- [x] UI, Domain Layer내에 Model 관련하여 중복된 코드 수정 및 삭제
- [x] ViewMode 클릭 이벤트 및 버튼 클릭 상태 관련 코드 개선
- [x] <del> 각 프래그먼트 xml 합치기 혹은 개선 (현재 모두 유사한 구조임)</del>
- [x] view Holder Model id 값 개선
- [x] 메인 요리 화면 - MainDishViewModel 개선 (menu 리스트, 뷰모드 버튼, 정렬 스피너 적용가능하도록)

다른 feature 구현 상에서 개선할 수도 있음

### 🔍 참고
[PR#20](https://github.com/woowa-techcamp-2022/android-banchan-05/pull/20), [PR#22](https://github.com/woowa-techcamp-2022/android-banchan-05/pull/22)
