### ISSUE TITLE
[FEATURE] 기본 DataLayer단 구축하기(Local & Remote)

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-banchan-05#3]
### 📌 내용
data layer 단의 기본적인 boiler plate 코드 추가하기

### 🛠 ToDo
- [x] Database boiler plate 코드 구현
- [x] 데이터 설계를 기반으로 필요한 Dao 코드 추가
- [x] Retrofit bolier plate 코드 구현
- [x] 기획서를 기반으로 필요한 API Service 코드 추가
