### ISSUE TITLE
[FEATURE] 최근 본 상품 화면 UI 및 기능 구현

### ISSUE THREAD

**Issue by eshc123** [woowa-techcamp-2022/android-banchan-05#31]
### 📌 내용
최근 본 상품 화면 UI 및 기능 구현

### 🛠 ToDo
- [x] 최근 본 상품 UI
- [x] 상품 클릭 시 화면 전환
- [x] 상품 내 장바구니 클릭 시 DB 저장 구현
- [x] 최근 본 상품 관련 DB 구성
- [x] 상세화면 진입 시 최근 본 상품 추가 기능 구현
