### ISSUE TITLE
[FEATURE] 최근 본 항목 화면 Data Layer 구성하기

### ISSUE THREAD

**Issue by eshc123** [woowa-techcamp-2022/android-banchan-05#32]
### 📌 내용
최근 본 항목 화면에서 로컬 DB를 포함한 Data Layer 구성

### 🛠 ToDo
- [x] Room 라이브러리 사용하여 최근 본 항목 화면 관련 Local DB 구축 
- [x] 최근 본 항목 정보 Local DB로부터 받아오기
- [x] 받아온 데이터 view에 바인딩 해주기
