### ISSUE TITLE
[FEATURE] 홈 화면에서 메뉴 클릭 시, 상세 화면으로 이동하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-banchan-05#35]
### 📌 내용
홈 화면에서 메뉴 아이템 클릭 시, 상세 화면으로 이동하고
이 때 선택한 메뉴의 id 값 전달하기

### 🛠 ToDo
- [x] 메뉴 아이템 클릭 시, Fragment에서 해당 아이템의 id를 얻을 수 있는 로직 구현하기
- [x] 홈 화면에서 상세 화면으로 Fragment 전환하기
- [x] 상세 화면으로 Fragment 전환할 때, 메뉴 id 전달하기
- [x] 상세 화면에서 백버튼 클릭 시, 이전 화면으로 이동하도록 수정하기

**Comment by aurora32s** [comment]
일단 event 전달은 implement로 해두었지만, 내일 팀원과 함께 의견을 나눠보고 코드 수정 예정
