### ISSUE TITLE
[FIX] Database Class 이름 중복으로 인해 발생한 Conflict 문제 수정

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-banchan-05#45]
### 📌 내용
Database Class 이름이 중복되어, 정상적으로 merge가 진행되지 않아,
이 부분을 dev에서 별도의 branch를 구성하여 수정할 예정입니다.

### 🛠 ToDo
- [x] fix branch 생성하기
- [x] 데이터베이스 단 에러 확인 및 수정하기
- [ ] 석준님에게 확인 요청하기
