### ISSUE TITLE
[FEATURE] 장바구니 화면 UI 구성하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-banchan-05#5]
### 📌 내용
장바구니 화면에 기본 Ui 구성하기
[100% Compose]

### 🛠 ToDo
- [x] 상단 앱 바 UI 구성하기(Backbutton event는 제외)
- [x] 좌측 상단의 아이템 선택 버튼과 우측 상단의 삭제 버튼 UI 구성하기
- [x] 장바구니에 들어있는 아이템 Ui 구성하기
- [x] 상품 주문 금액, 배달료, 총 주문 금액 UI 구성하기
- [x] 주문하기 버튼과 무료 배달에 필요한 금액 Ui 구성하기
- [x] 최근 본 상품 아이템 Ui 구성하기
- [x] 최근 본 상품 아이템 리스트 UI 구성하기
