### ISSUE TITLE
[REFACTOR] 상세화면에서 발생하는 이슈 처리 및 에러 대응을 위한 UI 처리하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-banchan-05#58]
### 📌 내용
상세화면에서도 홈 화면에서와 마찬가지로 주문하기 버튼 클릭 시, Bottom Sheet가 나와
개수를 선택하고 장바구니에 추가하도록 UI 수정

### 🛠 ToDo
- [x] 상세 화면의 UI 꺠지는 문제 수정하기
- [x] 장바구니 담기 버튼이 한번만 담기는 문제 수정하기
- [x] 메뉴 설명란 추가하기
- [x] 코드 정리하기
- [x] 서버로부터 메뉴 상세 정보 받아오는 도중 문제가 발생했을 때 UI 처리하기
- [x] 장바구니에 추가할 때 문제가 발생한 경우의 UI 처리하기

**Comment by aurora32s** [comment]
### 🌹 추가
- [ ] 상세 화면의 UI 꺠지는 문제 수정하기
- [ ] 장바구니 담기 버튼이 한번만 담기는 문제 수정하기
- [ ] 메뉴 설명란 추가하기
- [ ] 코드 정리하기
- [ ] 서버로부터 메뉴 상세 정보 받아오는 도중 문제가 발생했을 때 UI 처리하기
- [ ] 장바구니에 추가할 때 문제가 발생한 경우의 UI 처리하기
