### ISSUE TITLE
[FEATURE] 주문내역 리스트 화면 UI 구성하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-banchan-05#59]
### 📌 내용
주문 내역이 리스트로 보이는 화면의 기본 UI 구성하기

### 🛠 ToDo
- [x] 상단 프로필 사진 클릭 시, 주문 내역 리스트로 이동하기
- [x] 주문 내역 리스트 아이템 UI 구성하기
- [x] 주문 내역 리스트 Model과 ViewHolder 추가하기
- [x] 주문 내역 리스트 구현하기
