### ISSUE TITLE
[FEATURE] 주문 내역 상세 정보 화면 UI 구성하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-banchan-05#60]
### 📌 내용
주문 내역 리스트에서 리스트 아이템을 클릭 했을 때, 해당 주문의 상세 정보를 보여주는 화면 UI 구성하기

### 🛠 ToDo
- [x] 주문 내역 리스트에서 아이템 클릭 시, 주문 내역 상세 화면으로 이동
- [x] 상단 배송 상태 정보 UI 구성하기
- [x] 중간 주문 메뉴 아이템 UI 구성하기
   - 주문 내역 리스트 아이템과 재활용할 수 있도록 고민해보자
- [x] 하단 주문 금액 정보 석준님 코드를 재활용하기
