### ISSUE TITLE
[REFACTOR] 장바구니 Bottom Sheet 코드 리뷰 사항 반영

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-banchan-05#64]
### 📌 내용
[FEATURE] #43 장바구니 Bottom Sheet에서 장바구니 추가 로직 구현하기 #56 
에 작성된 comment에서 '권장' 사항 부분 코드에 반영하기

### 🛠 ToDo
- [x] OrderBottomSheetDialog Builder Pattern 부분 공부해보고 코드 수정하기
- [x] fragment의 flow collect 부분 repeatOnLifecycler로 수정하기
   - flow에 대해서 더 학습해보기
- [x] viewModelScope.launch를 통해 job을 반환하던 코드 수정하기

👇🏻 요부분!
```kotlin
fun name() = viewModelScope.launch {}
```
