### ISSUE TITLE
[REFACTOR] 최근 본 상품 UI 구성 코드 개선

### ISSUE THREAD

**Issue by eshc123** [woowa-techcamp-2022/android-banchan-05#65]
### 📌 내용
#51 최근 본 상품 UI 구성 PR 개선

### 🛠 ToDo
- [ ] 인터페이스 내 주석 달기
- [ ] Time Util 개선
- [ ] GridItemDecoration 내 spanCount 개선
