### ISSUE TITLE
[REFACTOR] 장바구니 화면 UI 구성 코드 개선

### ISSUE THREAD

**Issue by eshc123** [woowa-techcamp-2022/android-banchan-05#69]
### 📌 내용
#52 장바구니 화면 UI 구성 PR 코드 개선

### 🛠 ToDo
- [ ] DELIVERY_FEE -> DEFAULT_DELIVERY_FEE
- [ ] CartMenuModel - price default 값 삭제
- [ ] 불필요한 Import 제거
- [ ] ModelRecyclerAdapter - updateModelsAtPosition 매개변수 및 함수명 개선
- [ ] ModelRecyclerAdapter - updateModelAtPosition 사용 시 position 값 개선
- [ ] 주문하기 버튼 - 최소금액을 확인~ -> 00,000원부터 주문할 수 있어요
- [ ] deliveryFee 등 const 값 사용
- [ ] OrderInfoViewHolder 개선

추가
- [ ] Limit -> Minimun
