### ISSUE TITLE
[FEATURE] 모든 화면의 최상단 앱바 UI 및 기능 구현

### ISSUE THREAD

**Issue by eshc123** [woowa-techcamp-2022/android-banchan-05#74]
### 📌 내용
모든 화면의 최상단 앱바 UI 및 기능 구현

### 🛠 ToDo
- [x] 화면에 맞는 앱바 UI 구성
- [x] 각 화면 별 UI에 맞게 기능 구현
  - [x] 백버튼 기능
  - [x] 장바구니 아이콘 - 기능 및 데이터 연동
  - [x] 유저 아이콘(주문 내역) - 기능 및 데이터 연동
