### ISSUE TITLE
[REFACTOR][FEATURE] 장바구니 화면 기능 구현 코드 개선

### ISSUE THREAD

**Issue by eshc123** [woowa-techcamp-2022/android-banchan-05#84]
### 📌 내용
#80 장바구니 화면 UI 및 기능 구현 코드 개선, 로컬 DB 연동

### 🛠 ToDo

- [x] CartMenuViewHolder - settext -> text = ~ 로 변경
- [x] MainActivity - initViews() (Appbar 수정 적용 시 변경될 수도 있음)
- [x] RecentFragment로 replace 시 태그와 함께
- [x] viewModel 선언 위치 조정
- [x] Cart 화면 내 최근 본 상품 클릭 시 상세보기 화면 이동
- [x] CartOrderViewHolder 코드 수정 (https://github.com/woowa-techcamp-2022/android-banchan-05/pull/52#discussion_r950635044 참고)
- [x] 로컬 DB 연동

**Comment by eshc123** [comment]
기존에 있던 Toast 확장 함수 만들기 (https://github.com/woowa-techcamp-2022/android-banchan-05/pull/80#discussion_r951161541 참고) 는 #67 공통 코드 수정 PR에 추가하였습니다.
