### ISSUE TITLE
[REFACTOR] 장바구니 코드 개선 #85 PR 참고

### ISSUE THREAD

**Issue by eshc123** [woowa-techcamp-2022/android-banchan-05#95]
### 📌 내용
장바구니 코드 개선 #85 PR 참고

### 🛠 ToDo
- [ ] MenuModel - CellType 개선
- [ ] CartEntitly - selected 기본값 추가
- [ ] OrderInfoModel - deliverFee 프로퍼티 삭제
- [ ] CartFragment - CartMenuUiModel 관련 (https://github.com/woowa-techcamp-2022/android-banchan-05/pull/85#discussion_r952694798 참고)
- [ ] CartFragment - UiStateModel 관련
- [ ] CartViewModel - fetchCartMenus -collectLatest 파라미터 
- [ ] CartViewModel - check 관련 코드 개선
- [ ] CartViewModel - cartOrder 코드 개선
- [ ] CartViewModel - cartMenus 코드 개선
