### ISSUE TITLE
[FEATURE] 장바구니 화면에서 주문하기 로직 구현하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-banchan-05#96]
### 📌 내용
장바구니 화면에서 구매하기 버튼 클릭 시, 주문하고 주문 상세 내역으로 이동하기!

### 🛠 ToDo
- [ ] 장바구니 화면에서 주문 버튼 클릭 시, 주문 DB에 추가
- [ ] 주문한 아이템 DB에서 전부 삭제
- [ ] 주문 성공 시, 주문 상세 화면으로 이동하기
- [ ] AlarmManager 시작하기
- [ ] 주문 상세 화면에서 progress bar 줄어드는거 확인하기
- [ ] 알림 정상적으로 오는거 확인하기
- [ ] 주문 내역 리스트에서 배달 상태값  변경 확인하기
