### ISSUE TITLE
[REFACTOR] 배달완료 처리 후, 알림 메세지 띄워줄 수 있도록 코드 수정하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-banchan-05#99]
### 📌 내용
현재는 배달 완료 처리를 해주는 DB 작업과 알림 생성 작업이 병렬적으로 수행되고 있습니다.
이 부분을 DB 작업이 완료된 이후 성공적으로 끝났다면 알림을 생성할 수 있도록 수정할 예정입니다.

### 🛠 ToDo
- [x] Background 작업에 대해서 공부하기
- [x] Background에서 Foreground 요청 부분 공부하기
- [x] DB 작업 완료 후, 알림 생성하기
